import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import '@/styles/main.css'
import Follow from "@/component/follow"
import Option from '@/component/option'
const ulrTest = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Anime_Girl_with_cat.svg/1200px-Anime_Girl_with_cat.svg.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter Clone Games - Next.js',
  description: 'Generated by JetShen',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="homeContainer">
          <div className="navegation">
            <div className="miniN">
              <Image src={ulrTest}
                alt="Picture of the author"
                width={0}
                height={0}
                sizes="100vw"
                style={{ width: '50%', height: 'auto' }}
                className='profilePostImg' />
              <strong>Username</strong>
              <p>@username</p>
            </div>
            <ul className="options">
              <Option username='Username' />
            </ul>
          </div>
          <div className="main">
            {children}
          </div>
          <div className="follow">
            <Follow />
          </div>
        </div>
      </body>
    </html>
  )
}
